# Generated by Django 5.2.7 on 2025-10-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccelerometerData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sample_at_ms", models.BigIntegerField()),
                (
                    "sample_at_source",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("event_seq", models.BigIntegerField(blank=True, null=True)),
                ("acvl", models.FloatField(blank=True, null=True)),
                ("xyz_count", models.IntegerField(blank=True, null=True)),
                (
                    "ref_station_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("ref_scanned_at_ms", models.BigIntegerField(blank=True, null=True)),
                ("time_label", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "accelerometer_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Devices",
            fields=[
                (
                    "device_mac",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("first_seen_ms", models.BigIntegerField(blank=True, null=True)),
                ("last_seen_ms", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "devices",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Families",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("family_id", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "families",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MotionData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at_ms", models.BigIntegerField(blank=True, null=True)),
                ("event_seq", models.BigIntegerField(blank=True, null=True)),
                ("time_label", models.CharField(blank=True, max_length=64, null=True)),
                ("motion_data_total", models.IntegerField(blank=True, null=True)),
                ("station_id", models.CharField(blank=True, max_length=64, null=True)),
                ("room_type", models.IntegerField(blank=True, null=True)),
                ("rssi", models.IntegerField(blank=True, null=True)),
                ("scanned_at_ms", models.BigIntegerField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "motion_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PedometerData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sample_at_ms", models.BigIntegerField()),
                ("t_mark_day", models.CharField(blank=True, max_length=16, null=True)),
                ("t_mark_md", models.CharField(blank=True, max_length=16, null=True)),
                ("pedo_d0", models.IntegerField(blank=True, null=True)),
                ("pedo_d_1", models.IntegerField(blank=True, null=True)),
                ("pedo_d_2", models.IntegerField(blank=True, null=True)),
                ("sender_id", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "pedometer_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProximityData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sample_at_ms", models.BigIntegerField()),
                (
                    "sample_at_source",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("event_seq", models.BigIntegerField(blank=True, null=True)),
                ("seq_diff", models.BigIntegerField(blank=True, null=True)),
                ("acvl", models.FloatField(blank=True, null=True)),
                ("cvl_increment", models.FloatField(blank=True, null=True)),
                ("xyz_count", models.IntegerField(blank=True, null=True)),
                (
                    "ref_station_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("ref_scanned_at_ms", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "proximity_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RtsStationRssi",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("station_alias", models.CharField(max_length=64)),
                ("station_mac", models.CharField(blank=True, max_length=64, null=True)),
                ("rssi", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "rts_station_rssi",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Stations",
            fields=[
                (
                    "station_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "station_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("room_type", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "db_table": "stations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="XyzCoordinates",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("point_idx", models.IntegerField()),
                ("x", models.FloatField(blank=True, null=True)),
                ("y", models.FloatField(blank=True, null=True)),
                ("z", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "xyz_coordinates",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="SensorData",
        ),
    ]
